### ISSUE TITLE
Please update the package version，Thanks!

### ISSUE THREAD

**Issue by peachtang** [xxxxst/monaco-editor-locales-plugin#3]
![image](https://user-images.githubusercontent.com/22881737/110903556-983ac280-8342-11eb-94f3-23aa1b12895a.png)
help me thanks! @xxxxst

**Comment by xxxxst** [comment]
You seem to be using Chinese, so I will reply you in Chinese。

monaco-editor内置的多国语言支持最迟的版本是0.14.6，之后的版本只有英语。

本插件的翻译文本来自于0.14.6，如果后续的版本文本有变更，
需要自行翻译，通过mapLanguages参数将翻译文本传进去。

可以设置logUnmatched参数，在控制台中打印所有未被翻译的文本。

```js
new MonacoLocalesPlugin({
    languages: ["zh-cn"],
    logUnmatched: true,
    mapLanguages: {
        "zh-cn": {
            "chinese": "中文"
         }
    },
}),
```
插件仅提供语言转换的方法，不处理翻译缺失问题。
Thanks
